version: '3'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.2
    container_name: es
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=1
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - morphnet

  mysql:
    image: mysql:8
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=morphpass1
      - MYSQL_DATABASE=morpheus
      - MYSQL_INITDB_SKIP_TZINFO=true
    volumes:
      - ./mysqldata:/var/lib/mysql
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=$$MYSQL_ROOT_PASSWORD 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
    networks:
      - morphnet

  rmq:
    image: rabbitmq:3.12
    container_name: rmq
    volumes:
      - ./rmqconfig/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rmqdata:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics ping || exit 1
    networks:
      - morphnet

  morpheus:
    image: morpheus:latest
    # image: ghcr.io/tryfan/morpheus:5.4.5-2
    container_name: morpheus
    environment:
      - MORPHEUS_APPLIANCE_URL=https://localhost
      - MORPHEUS_ELASTICSEARCH_ES_HOSTS={'es' => 9200}
      - MORPHEUS_ELASTICSEARCH_AUTH_USER=elastic
      - MORPHEUS_ELASTICSEARCH_AUTH_PASSWORD=elastic
      - MORPHEUS_MYSQL_HOST={'mysql' => 3306}
      - MORPHEUS_MYSQL_MORPHEUS_DB_USER=root
      - MORPHEUS_MYSQL_MORPHEUS_DB=morpheus
      - MORPHEUS_MYSQL_MORPHEUS_PASSWORD=morphpass1
      - MORPHEUS_RABBITMQ_HOST=rmq
      - MORPHEUS_RABBITMQ_VHOST=/
      - MORPHEUS_RABBITMQ_QUEUE_USER=morpheus
      - MORPHEUS_RABBITMQ_QUEUE_USER_PASSWORD=morphpass1
      - MORPHEUS_UI_MAX_MEMORY_MB=3584
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./morphdata:/var/opt/morpheus
      - ./morphlogs:/var/logs/morpheus
    depends_on:
      es:
        condition: service_healthy
      mysql:
        condition: service_healthy
      rmq:
        condition: service_healthy
    networks:
      - morphnet

networks:
  morphnet:
    driver: bridge

volumes:
  esdata:
    driver: local